src/AppBundle/Entity/Sender.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Sender
 *
 * @ORM\Table(name="app_sender")
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="proprietaire", type="string")
 * @ORM\DiscriminatorMap({"membre" = "SenderMembre"})
 */
abstract class Sender
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Mail",
     *                mappedBy="sender", cascade={"persist","remove"})
     */
    private $mails;


    /**
     * Constructor
     */
    public function __construct()
    {
        $this->mails = new \Doctrine\Common\Collections\ArrayCollection();
    }

    abstract function getOwner();

    /**
     * Retourne la liste des envois en attente
     *
     * @return array
     */
    public function getNotSentMails()
    {
        $mails = array();
        /** @var Mail $mail */
        foreach($this->mails as $mail)
        {
            if((!$mail->isSentByMail()) && (!$mail->isPrinted()))
            {
                $mails[] = $mail;
            }
        }
        return $mails;
    }

    /**
     * retourne la liste des envois déjà effectué, soit par e-mail ou courrier
     *
     * @return array
     */
    public function getSentMails()
    {
        $mails = array();
        /** @var Mail $mail */
        foreach($this->mails as $mail)
        {
            if($mail->isSentByMail() || $mail->isPrinted())
            {
                $mails[] = $mail;
            }
        }
        return $mails;
    }


    /**
     * Add mail
     *
     * @param Mail $mail
     *
     * @return Sender
     */
    public function addMail(Mail $mail)
    {
        $this->mails[] = $mail;
        if($mail->getSender() != $this)
        {
            $mail->setSender($this);
        }
        return $this;
    }

    /**
     * Remove mail
     *
     * @param Mail $mail
     */
    public function removeMail(Mail $mail)
    {
        $this->mails->removeElement($mail);
    }

    /**
     * Get mails
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMails()
    {
        return $this->mails;
    }
}

src/AppBundle/Form/Facture/FactureRepartitionType.php
<?php

namespace AppBundle\Form\Facture;

use AppBundle\Form\Creance\CreanceRepartitionType;
use AppBundle\Form\Rappel\RappelRepartitionType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;

class FactureRepartitionType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('creances', CollectionType::class,
                array(
                    'label' => 'Créances',
                    'entry_type' => new CreanceRepartitionType()
                ))
            ->add('rappels', CollectionType::class,
                array(
                    'label' => 'Rappels',
                    'entry_type' => new RappelRepartitionType()));

        //fin de la fonction builder
    }

    public function configureOptions(\Symfony\Component\OptionsResolver\OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Facture'
        ));
    }


    public function getBlockPrefix()
    {
        return 'app_bundle_facture_repartition';
    }

}

src/AppBundle/Controller/FactureController.php
<?php

namespace AppBundle\Controller;

/* Symfony */
use AppBundle\Utils\ListUtils\ListKey;
use AppBundle\Utils\Response\ResponseFactory;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;

/* Entity */
use AppBundle\Entity\Facture;

/* Elastica repository */
use AppBundle\Search\Facture\FactureRepository;
use AppBundle\Search\Facture\FactureSearch;
use AppBundle\Search\Facture\FactureSearchType;

/* routing */
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use AppBundle\Utils\Menu\Menu;

/* Service */
use AppBundle\Utils\Export\Pdf;
use AppBundle\Utils\ListUtils\ListStorage;
use AppBundle\Utils\Finances\FacturePrinter;
use AppBundle\Search\Mode;

/**
 * Class FactureController
 * @package AppBundle\Controller
 *
 * @Route("/intranet/finance/facture")
 */
class FactureController extends Controller
{

    /**
     * @Route("/search", options={"expose"=true})
     * @Menu("Recherche de factures",block="finances",order=2,icon="search")
     * @param Request $request
     * @Template("AppBundle:Facture:page_recherche.html.twig")
     * @return Response
     *
     *
     */
    public function searchAction(Request $request){


        $factureSearch = new FactureSearch();

        $searchForm = $this->createForm(new FactureSearchType(),$factureSearch);


        /** @var ListStorage $sessionContainer */
        $sessionContainer = $this->get('list_storage');
        $sessionContainer->setRepository(ListKey::FACTURES_SEARCH_RESULTS,'AppBundle:Facture');


        $searchForm->handleRequest($request);
        if ($searchForm->isValid()) {

            $factureSearch = $searchForm->getData();

            $elasticaManager = $this->container->get('fos_elastica.manager');

            /** @var FactureRepository $repository */
            $repository = $elasticaManager->getRepository('AppBundle:Facture');

            $results = $repository->search($factureSearch);

            //get the search mode
            $mode = $searchForm->get(Mode::FORM_FIELD)->getData();
            switch($mode)
            {
                case Mode::INCLUDE_PREVIOUS: //include new results with the previous
                    $sessionContainer->addObjects(ListKey::FACTURES_SEARCH_RESULTS,$results);
                    break;
                case Mode::EXCLUDE_PREVIOUS: //exclude new results to the previous
                    $sessionContainer->removeObjects(ListKey::FACTURES_SEARCH_RESULTS,$results);
                    break;
                case Mode::STANDARD:
                default:
                    $sessionContainer->setObjects(ListKey::FACTURES_SEARCH_RESULTS,$results);

            }

        }


        return array('searchForm'=>$searchForm->createView(),'list_key'=>ListKey::FACTURES_SEARCH_RESULTS);

    }


    /**
     * @Route("/show/{facture}", options={"expose"=true})
     * @param Facture $facture
     * @ParamConverter("facture", class="AppBundle:Facture")
     * @param Request $request
     * @return Response
     * @Template("AppBundle:Facture:show_modal.html.twig")
     */
    public function showAction(Request $request,Facture $facture){

        return  array('facture' => $facture);
    }


    /**
     * @Route("/remove/{facture}", options={"expose"=true})
     * @param Facture $facture
     * @ParamConverter("facture", class="AppBundle:Facture")
     * @param Request $request
     * @return Response
     */
    public function removeAction(Request $request,Facture $facture)
    {
        if($facture->isRemovable())
        {
            $this->get('app.repository.facture')->remove($facture);
            return ResponseFactory::ok();
        }
        return ResponseFactory::conflict('La facture a déjà été payée.');
    }

    /**
     * Create a PDF and send it to the client browser
     *
     * @param Facture $facture
     * @Route("/print/{facture}", options={"expose"=true})
     * @return Response
     * @ParamConverter("facture", class="AppBundle:Facture")
     */
    public function printAction(Facture $facture)
    {

        /** @var FacturePrinter $printer */
        $printer = $this->get('app.facture_printer');
        /** @var Pdf $pdf */
        $pdf = $printer->factureToPdf($facture);

        /*
         * Ajout de l'adresse
         *
         * todo NUR à faire
         */
        //$adresse = $facture->getDebiteur()->getOwner()->getAdresseExpedition();

        //$pdf->addAdresseEnvoi($adresse);


        $filePath = $this->getParameter('cache_facture_dir');
        $fileName = 'facture_'.$facture->getId().'.pdf';

        $fs = new Filesystem();

        if(!$fs->exists($filePath))
        {
            $fs->mkdir($filePath);
        }


        /*
         * Save the PDF in cache dir
         */
        $pdf->Output($filePath.$fileName,'F');

        $response = new BinaryFileResponse($filePath.$fileName);
        $response->setContentDisposition(
            ResponseHeaderBag::DISPOSITION_ATTACHMENT
            //'Facture_'.$facture->getId().'.pdf' //change file name
        );

        return $response;
    }




}

src/AppBundle/Resources/views/Facture/page_recherche.html.twig
{% extends "AppBundle:Layout:layout.html.twig" %}


{% block titre %}Recherche de facture{% endblock %}

{% block content %}

    <div class="ui page grid">
        <div class="column">
            <div class="row">

                {% include "AppBundle:Facture:searchForm.html.twig" with {'form':searchForm} %}

                <div class="ui divider"></div>
            </div>

            <div class="row">

                {{ list_caller.Session(list_key)|raw }}

            </div>
        </div>
    </div>


{% endblock %}

src/AppBundle/Resources/views/Facture/searchForm.html.twig
{% form_theme form 'AppBundle:Form:form_search_accordion.html.twig' %}

{% form_theme form.mode 'AppBundle:Form:default_widgets.html.twig' %}

{{ form_start(searchForm, {'attr': {'class': 'ui form'}}) }}

<div class="ui top attached message">
    <h4 class="ui header">Recherche de facture</h4>
</div>

<div class="ui bottom attached segment">

    <div class="ui grid">
        <div class="eight wide column">
            {{ form_row(form.id) }}
            {{ form_row(form.intervalDateCreation) }}
            {{ form_row(form.intervalDatePayement) }}
            {{ form_row(form.intervalMontantEmis) }}
            {{ form_row(form.intervalMontantRecu) }}
        </div>
        <div class="eight wide column">

            {{ form_row(form.statut) }}
            {{ form_row(form.nombreRappels) }}
            {{ form_row(form.debiteur) }}
            {{ form_row(form.titreCreance) }}


        </div>
    </div>

    <div class="ui divider"></div>


    <div class="ui grid">
        <div class="eight wide column">
            {{ form_row(form.mode) }}
        </div>
        <div class="eight wide right aligned column">
            <input type="submit" value="Rechercher" class="ui blue submit button">
        </div>
    </div>


    {{ form_rest(searchForm) }}

</div>
{{ form_end(searchForm) }}

src/AppBundle/Resources/views/Facture/show_modal.html.twig
{% extends 'AppBundle:Templates:modal_small.html.twig' %}

{% block header %}
    Détail de la facture N°{{ facture.id }}
{% endblock %}

{% set hasPayement = facture.hasPayement() %}

{% block content %}
    <table class="ui definition table">
        <tbody>
        <tr>
            <td>Statut</td>
            <td>
                {{ facture|facture_state_detail|raw }}
            </td>
        </tr>
        <tr>
            <td>Date de création</td>
            <td>{{ facture.dateCreation|date(global_date_format) }}</td>
        </tr>



        {% if hasPayement %}
        <tr>
            <td>Date de payement</td>
            <td>
                {{ facture.datePayement|date(global_date_format) }}

                {{ modal_caller('<a class=" "><i class="zoom blue icon"></i>Voir le payement</a>',path('app_payement_show',{'payement':facture.payement.id})) }}
            </td>
        </tr>
        {% endif %}

        <tr>
            <td>Propriétaire</td>
            <td>
                {{ facture.debiteur.getOwnerAsString() }}
            </td>
        </tr>

        <tr>

            <td>Envoie par courrier</td>
            <td>

                {#
                {% include 'AppBundle:Adresse:show_format_postal.html.twig' with {'adresseExpedition':facture.debiteur.owner.adresseExpedition} %}

                #}
            </td>
        </tr>

        <tr>

            <td>Envoie par e-mail</td>
            <td>
                {#
                {% include 'AppBundle:Email:show_liste_expedition.html.twig' with {'listeEmailsExpedition':facture.debiteur.owner.listeEmailsExpedition} %}
                #}
            </td>
        </tr>



        </tbody>
    </table>

    <table class="ui celled table">
        <thead>
        <tr>
            <th rowspan="2">Créances et Rappels</th>
            <th>Montant émis</th>
            {% if hasPayement %}
            <th>Reçu</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for creance in facture.creances %}
            <tr>
                <td>

                    {{ modal_caller('<i class="zoom blue icon"></i>',path('app_creance_show',{'creance':creance.id})) }}


                    <b>{{ creance.titre }}</b>

                    {% if creance.remarques is not empty %}
                        <br>

                        Remarque: {{ creance.remarques }}
                    {% endif %}
                </td>
                <td>{{ creance.montantEmis|money }}</td>

                {% if hasPayement %}
                    {% if creance.montantRecu >= creance.montantEmis %}
                        <td class="positive">{{ creance.montantRecu|money }}</td>
                    {% else %}
                        <td class="negative">{{ creance.montantRecu|money }}</td>
                    {% endif %}
                {% endif %}
            </tr>



        {% endfor %}
        {% for rappel in facture.rappels %}
            <tr>
                <td>Rappel N°{{ loop.index }}</td>
                <td>{{ rappel.montantEmis|money }}</td>
                {% if hasPayement %}
                    {% if rappel.montantRecu >= rappel.montantEmis %}
                        <td class="positive">{{ rappel.montantRecu|money }}</td>
                    {% else %}
                        <td class="negative">{{ rappel.montantRecu|money }}</td>
                    {% endif %}
                {% endif %}
            </tr>
        {% endfor %}

        <tr>
            <td class="right aligned">Total</td>
            <td>{{ facture.montantEmis|money }}</td>
            {% if hasPayement %}
                {% if facture.montantRecu >= facture.montantEmis %}
                    <td class="positive">{{ facture.montantRecu|money }}</td>
                {% else %}
                    <td class="negative">{{ facture.montantRecu|money }}</td>
                {% endif %}
            {% endif %}
        </tr>

        </tbody>
    </table>
{% endblock %}